[tox]
envlist = py38,py39,py310,py311,py12
skipsdist = True

[testenv]
deps=
    pkgconfig
    Jinja2
    pytest
    pytest-asyncio
    cython>=3

commands =
    pip install .
    py.test {posargs}

setenv =
    CFLAGS='-stdlib=libc++'
    CXXFLAGS='-stdlib=libc++'

[testenv:stubtest]
skip_install = True
deps =
    Jinja2
    basedpyright
    mypy
    pytest
    pytest-asyncio
setenv =
    PYTHONPATH = {toxinidir}
commands =
    pytest {toxinidir}/test/stubtest
    python -m mypy.stubtest capnp --concise --ignore-disjoint-bases --allowlist {toxinidir}/test/stubtest/allowlist.txt --mypy-config-file {toxinidir}/test/stubtest/mypy.ini
    basedpyright --verifytypes capnp --ignoreexternal
